config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :boards, only: [:index, :create, :new, :edit, :update,:destroy] do
    resources :articles
    resources :calendars
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/boards/:link', to: 'boards#show'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :board
  mount_uploader :photo, PhotoUploader
  validates :title, presence: true
  validates :photo, presence: true
end

app/models/board.rb
require 'json'
require "open-uri"

class Board < ApplicationRecord
  has_many :calendars, dependent: :destroy
  has_many :articles, dependent: :destroy

  validates :name, presence: true
  validates :location, presence: true

  def meteo
    f = "http://api.openweathermap.org/data/2.5/forecast?q="
    f += self.location
    f += "&appid="
    f += ENV["METEO_KEY"]
    f += "&units=metric"
    serialized_meteo = open(f).read
    JSON.parse(serialized_meteo)["list"]
  end
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :board

  validates :title, presence: true
  validates :date, presence: true
  validates :location, presence: true
  validates :city, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @board = Board.find(params[:board_id])
    @articles = Article.where(board: @board)
  end

  def new
    @board = Board.find(params[:board_id])
    @article = Article.new
  end

  def create
    @article = Article.new(create_params)
    @board = Board.find(params[:board_id])
    @article.board = @board
    if @article.save
      redirect_to board_articles_path(@board)
    else
      render :new
    end
  end

  def edit
    @board = Board.find(params[:board_id])
    @article = Article.find(params[:id])
  end

  def update
    @board = Board.find(params[:board_id])
    @article = Article.find(params[:id])
    @article.update(create_params)
    redirect_to board_articles_path(@board)
  end

  def destroy
    @board = Board.find(params[:board_id])
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to board_articles_path(@board)
  end

  private

  def create_params
    params.require(:article).permit(:title, :date, :end_date, :photo)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :authenticate_user! , only: [:show]

  def index
    @boards = Board.all
  end

  def show
    today = Time.now
    @board = Board.find_by(link: params[:link])
    @meteo = @board.meteo
    @meteotime = ["Maintenant", "Dans 3h","Dans 6h"]
    @calendars = Calendar.where(board: @board).where("date > ?", Time.now - 1.hours).order(:date)
    @articles = Article.where(board: @board).where("end_date >= ?", Time.now).where("date <= ?", Time.now)
  end

  def new
    @board =Board.new
  end

  def create
    @board = Board.new(create_params)
    @board.link = (0...8).map { (65 + rand(26)).chr }.join
    if @board.save
      redirect_to board_path(@board.link)
    else
      render :new
    end
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    @board.update(create_params)
    redirect_to boards_path()
  end

  def destroy
    @board = Board.find(params[:id])
    @board.destroy
    redirect_to boards_path
  end

  private

  def create_params
    params.require(:board).permit(:name, :location)
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  def index
    @board = Board.find(params[:board_id])
    @calendars = Calendar.where(board: @board).order(:date)
  end
  
  def show
  end

  def new
    @board = Board.find(params[:board_id])
    @calendar = Calendar.new
  end

  def create
    @calendar = Calendar.new(create_params)
    @board = Board.find(params[:board_id])
    @calendar.board = @board
    if @calendar.save
      redirect_to board_calendars_path(@board)
    else
      render :new
    end
  end

  def edit
    @board = Board.find(params[:board_id])
    @calendar = Calendar.find(params[:id])
    
  end

  def update
    @board = Board.find(params[:board_id])
    @calendar = Calendar.find(params[:id])
    @calendar.update(create_params)
    redirect_to board_calendars_path(@board)
  end

  def destroy
    @board = Board.find(params[:board_id])
    @calendar = Calendar.find(params[:id])
    @calendar.destroy
    redirect_to board_calendars_path(@board)
  end

  private

  def create_params
    params.require(:calendar).permit(:title, :date, :location, :city)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <%= simple_form_for([@board, @article]) do |f| %>
        <%= f.input :title %>
        <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"}  %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"}  %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container">
  <h1>Article pour la Board : <%= @board.name %> </h1>
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Titre</th>
        <th scope="col">Date début</th>
        <th scope="col">Date fin</th>
        <th scope="col">Photo</th>
        <th scope="col"><i class="far fa-trash-alt"></i></th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each_with_index do |article, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= link_to article.title ,edit_board_article_path(@board,article) %></td>
          <td><%= article.date.strftime('%d-%m-%y') if article.date %></td>
          <td><%= article.end_date.strftime('%d-%m-%Y') if article.end_date %></td>  
          <td><%= cl_image_tag article.photo ,width: 400 %></td>
          <td>
            <%= link_to board_article_path(@board,article),
              method: :delete,
              data: { confirm: "Are you sure?" } do %>
                <i class="far fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Add', new_board_article_path(@board), class: "btn btn-primary" %>
</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <%= simple_form_for([@board, @article]) do |f| %>
        <%= f.input :title %>
        <%= f.input :date, as: :string, required: false, input_html: {class: "datepicker"}  %>
        <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker"}  %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "add", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<h1>Articles#show</h1>
<p>Find me in app/views/articles/show.html.erb</p>

app/views/boards/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <%= simple_form_for(@board) do |f| %>
        <%= f.input :name %>
        <%= f.input :location %>
        <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<div class="container">
  <h1>Les boards</h1>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Ville</th>
        <th scope="col">Article</th>
        <th scope="col">Calendar</th>
        <th scope="col">Link</th>
        <th scope="col"><i class="far fa-trash-alt"></i></th>
      </tr>
    </thead>
    <tbody>
      <% @boards.each_with_index do |board, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= link_to board.name , edit_board_path(board) %></td>
          <td><%= board.location %></td>
          <td><%= link_to "Articles", board_articles_path(board) %>(<%=board.articles.size %>)</td>  
          <td><%= link_to "Calendars", board_calendars_path(board) %>(<%=board.calendars.size %>)</td>
          <td><%= link_to board.link , board_path(board.link) %></td>
          <td>
            <%= link_to board_path(board),
            method: :delete,
            data: { confirm: "Are you sure?" } do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Add', new_board_path, class: "btn btn-primary" %>
</div>

app/views/boards/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <%= simple_form_for(@board) do |f| %>
        <%= f.input :name %>
        <%= f.input :location %>
        <%= f.submit "add", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<meta http-equiv="refresh" content="300" />

<div class="page">
  <div id="time"></div>
  <div class="row">
    <div class="col-md-9 main">
      <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" data-interval="10000">
        <ol class="carousel-indicators">
        <% @articles.each_with_index do |article, index| %>
          <li data-target="#carouselExampleCaptions" data-slide-to="<%= index %>" class="<%= "active" if index == 0 %>"></li> 
        <% end %>
        </ol>
        <div class="carousel-inner">
          <%  @articles.each_with_index do |article, index| %>
            <div class="carousel-item <%= "active" if index == 0 %>" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path article.photo %>')">
              <div class="carousel-caption d-none d-md-block">
                <h5><%= article.title %></h5>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-md-3 calendars">
      <h3 class="text-center">Calendrier</h3>
      <hr>
      <div class="row">
        <% @calendars.each do |calendar| %>
          <div class="col-md-12 calendar">
            <div class="calendar-date text-center">
              <div>
                <div><%= calendar.date.strftime('%d') %></div>
                <div class="down"><%= calendar.date.strftime('%m') %></div>
              </div>
            </div>
            <div class="calendar-content">
              <div>
                <h4><%= calendar.title %></h4>
                <p><%= calendar.date.localtime.strftime('%Hh%M') %></p>
                <p><%= calendar.location %> - <%= calendar.city %></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row">
    <div id="news" class="col-md-9 news">
      <img id="news-img" class="img-fluid" src="" alt="">
      <div class="news-content">
        <h3 id="title">...</h3>
        <p id="description">...</p>
      </div>
    </div>
    <div class="col-md-3 meteo">
      <div class="row">
        <% 3.times do |x| %>
          <div class="col-md-4 text-center">
            <div class="meteo-today">
              <%= icon('fas', 'sun') if @meteo[x]["weather"][0]["icon"].chop == "01" %>
              <%= icon('fas', 'cloud-sun') if @meteo[x]["weather"][0]["icon"].chop == "02" %>
              <%= icon('fas', 'cloud') if @meteo[x]["weather"][0]["icon"].chop == "03" %>
              <%= icon('fas', 'cloud') if @meteo[x]["weather"][0]["icon"].chop == "04" %>
              <%= icon('fas', 'cloud-rain') if @meteo[x]["weather"][0]["icon"].chop == "09" %>
              <%= icon('fas', 'cloud-sun-rain') if @meteo[x]["weather"][0]["icon"].chop == "10" %>
              <%= icon('fas', 'bolt') if @meteo[x]["weather"][0]["icon"].chop == "11" %>
              <%= icon('fas', 'snowflake') if @meteo[x]["weather"][0]["icon"].chop == "13" %>
              <%= icon('fas', 'smog') if @meteo[x]["weather"][0]["icon"].chop == "50" %>
            </div>
            <div class="meteo-today">
              <%=  @meteo[x]["main"]["temp"].to_f.round %>°
            </div>
            <p><%= @meteotime[x] %></p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/boards/show.js.erb
const NewsAPI = require('newsapi');

const newsapi = new NewsAPI(<%= ENV["NEWS_KEY"] %>);
const news = () => {
  newsapi.v2.topHeadlines({
    country: 'fr'
  }).then(response => {
    for (let i=1; i<response.articles.length; i++) {
      setTimeout( function timer(){
        document.getElementById("title").innerText = response.articles[i].title;
        document.getElementById("description").innerText = response.articles[i].description;
        document.getElementById("news-img").src=response.articles[i].urlToImage;
      }, i*10000 );
    }
    console.log(response);
  });
}

setInterval(news(),200000);

app/views/calendars/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-md-4">
      <%= simple_form_for([@board, @calendar]) do |f| %>
        <%= f.input :title %>
        <%= f.input :date, as: :string, required: false, input_html: {class: "datetimepicker"}  %>
        <%= f.input :location %>
        <%= f.input :city %>
        <%= f.submit "Update", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/calendars/index.html.erb
<div class="container">
  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Titre</th>
        <th scope="col">Date</th>
        <th scope="col">Location</th>
        <th scope="col">City</th>
        <th scope="col"><i class="far fa-trash-alt"></i></th>
      </tr>
    </thead>
    <tbody>
      <% @calendars.each_with_index do |calendar, index| %>
        <tr class="<%= "table-dark" if calendar.date < Time.now %>">
          <th scope="row"><%= index + 1 %></th>
          <td><%= link_to calendar.title ,edit_board_calendar_path(@board,calendar) %></td>
          <td><%= calendar.date.localtime.strftime('%H:%M %d-%m-%Y') %></td>  
          <td><%= calendar.location %></td>
          <td><%= calendar.city %></td>
          <td>
            <%= link_to board_calendar_path(@board,calendar),
              method: :delete,
              data: { confirm: "Are you sure?" } do %>
                <i class="far fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Add', new_board_calendar_path(@board), class: "btn btn-primary" %>
</div>

app/views/calendars/new.html.erb
<h1>Calendars#new</h1>
<p>Find me in app/views/calendars/new.html.erb</p>

app/views/calendars/show.html.erb
<h1>Calendars#show</h1>
<p>Find me in app/views/calendars/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' unless params[:link] %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "logomachetti.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Boards", boards_path(), class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>